### ISSUE TITLE
Incorrect sigma parameters in .itp file?

### ISSUE THREAD

**Issue by rowanwalker96** [kolmank/interfaceff2gro#1]
Hi there,

I've recently noticed that the sigma parameters given in the generated .itp files are different to those given in the INTERFACEFF paper. The original paper sigma for SC4 is 4.15 A with the 12-6 LJ model. Therefore shouldn't the value be 4.15 /2^(1/6) = 3.697A in the .itp file? The sigma of the original paper is different with Gromacs sigma.

Best,
Rowan

**Comment by kolmank** [comment]
Hi Rowan,

Thank you for your input. I am sorry that I have not responded to you earlier but github never notified me about the opened issue. I fixed the issue that you mentioned some time ago (I got input from other user). I would also like to mention that there is new branch of the script that solves the problem of volume expansion during simulation. Apparently one has to define 1,4 pair interactions manually, I was thinking for long time that Gromacs does it automatically but it looks that I was wrong this time. Please have a look. As soon as I will finish testing it, I will merge it to the master branch.

Best regards,
Krzysztof
