### ISSUE TITLE
forcefield could not recognize atom C and its parameters

### ISSUE THREAD

**Issue by dwypy** [kolmank/interfaceff2gro#2]
Dear Kolmank

I am sorry to disturb you.  I want to do a graphite simulation. I download the interface2gro file from https://github.com/kolmank/interfaceff2gro.

When I run ./interface2gro.py DMF.car ,or other .car files, I get this error:

Running msi2lmp v3.9.8 / 06 Oct 2016

 Forcefield: Class II
 Forcefield file name: ./msi2lmp/frc_files/pcff_iff_v1_5_CNT_poly_solv.frc
 Output is recentered around geometrical center
 Output contains style flag hints
 System translated by: 0 0 0
 Reading car file: DMF.car
 Reading mdf file: DMF.mdf

 Building internal coordinate lists

 Reading forcefield file

 Get force field parameters for this system
 Unable to find angle data for hdm c_1 n
 Unable to find bondbond data for hdm c_1 n
 Unable to find bondangle data for hdm c_1 n
 Unable to find torsion data for hdm c_1 n c
 Unable to find midbonddihedral data for hdm c_1 n c
 Unable to find oop data for hdm c_1 n o_1
 Unable to find angleangle data for hdm c_1 n o_1

 Check parameters for internal consistency
 Writing LAMMPS data file DMF.data for Class II force field

Normal program termination

Traceback (most recent call last):
  File "./interfaceff2gro.py", line 288, in <module>
    gro_file.write(gro_format%(1,'SURF',mass2element[m[1]],m[0]+1,m[2][0]/10,m[2][1]/10,m[2][2]/10))
KeyError: 12.01115

Could you please give me some advice?

**Comment by kolmank** [comment]
Really sorry for late answer, I never got any notification about this issue. Unfortunately, the script only works with the surfaces from InterfaceFF 1.5 model database. Small molecules or multi-component systems do not work. I would suggest the CHARMM-GUI website for such systems.
